//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
namespace TikiBeeGame {
    public static class Logger {
        static bool LOGENEMY = false;
        static bool LOGPLAYER = false;
        static bool LOGPOWERUP = false;
        static bool LOGSOCIAL = false;
        static bool LOGHUD = false;
        static bool LOGGAME = false;
        static bool LOGCHARACTER = false;

        public static void logHud(string error) {
            if (LOGHUD) {
                Debug.Log(error);
            }
        }
        public static void logEnemy(string error) {
            if (LOGENEMY) {
                Debug.Log(error);
            }
        }
        public static void logPlayer(string error) {
            if (LOGPLAYER) {
                Debug.Log(error);
            }
        }
        public static void logPowerup(string error) {
            if (LOGPOWERUP) {
                Debug.Log(error);
            }
        }
        public static void logSocial(string error) {
            if (LOGSOCIAL) {
                Debug.Log(error);
            }
        }
        public static void logGame(string error) {
            if (LOGGAME) {
                Debug.Log(error);
            }
        }
        public static void logCharacter(string error) {
            if (LOGCHARACTER) {
                Debug.Log(error);
            }
        }
    }
}

