//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

namespace TikiBeeGame {
    public class PowerupController : MonoBehaviour {

        public int HEALTHBONUS = 0;
        public int SCOREBONUS = 0;
        public int CURRENCYBONUS = 0;

        public PowerupController() {
        }

        public virtual void spawn() {

            if (!this.gameObject.activeSelf) {
                this.gameObject.SetActive(true);
            }

            transform.position = SpawnPoint.getSpawnPointAtRandomInsideBoundsExcludeHud();
        }

        public virtual void OnBecameInvisible() {
            DestroyMe();
        }
        virtual public void OnTriggerEnter2D(Collider2D other) {
            Logger.logPowerup(other.tag + " hit OnTriggerEnter2D on " + this.tag);

            if (other.CompareTag("Player")) {
                PreferencesManager.getPlayerController().gainScore(SCOREBONUS);
                PreferencesManager.getPlayerController().gainHealth(HEALTHBONUS);
                PreferencesManager.getPlayerController().gainCurrency(CURRENCYBONUS);

				GetComponent<Animator>().SetTrigger("shouldDissappear");
            }
        }
        virtual public void OnTriggerStay2D(Collider2D other) {
            Logger.logPowerup(other.tag + " hit OnTriggerStay2D on " + this.tag);
        }
        virtual public void OnTriggerExit2D(Collider2D other) {
            //if (other.CompareTag("Player")) {
            //    DestroyMe();
            //}
        }
        virtual public void DestroyMe() {
            Logger.logPowerup("Destoring char " + this.tag);

            if (GetType() == typeof(HeartController)) {
                if (PreferencesManager.HEARTS_SPAWNED - 1 >= 0)
                    PreferencesManager.HEARTS_SPAWNED--;
            }
            if (GetType() == typeof(StarController)) {
                if (PreferencesManager.STARS_SPAWNED - 1 >= 0)
                    PreferencesManager.STARS_SPAWNED--;
            }
            if (GetType() == typeof(SpeedBoostController)) {
                if (PreferencesManager.SPEED_BOOST_SPAWNED - 1 >= 0)
                    PreferencesManager.SPEED_BOOST_SPAWNED--;
            }
            if (GetType() == typeof(PortalController)) {
                if (PreferencesManager.PORTALS_SPAWNED - 1 >= 0)
                    PreferencesManager.PORTALS_SPAWNED--;
            }

            if (this.gameObject != null) {
                Destroy(this.gameObject);
            }
        }
    }
}

