//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

namespace TikiBeeGame
{
	public class PowerupController : MonoBehaviour
		{

			public int HEALTHBONUS = 0;
            public int SCOREBONUS = 0;
            public int CURRENCYBONUS = 0;

			public PowerupController () {
			}

            public virtual void spawn() {

                if (!this.gameObject.activeSelf) {
                    this.gameObject.SetActive(true);
                }

                transform.position = SpawnPoint.getSpawnPointAtRandomInsideBoundsExcludeHud();
            }

            public virtual void OnBecameInvisible() {
                if (this.gameObject != null) {
                    DestroyMe();
                }
            }
            virtual public void OnTriggerEnter2D(Collider2D other) {
                Logger.logPowerup(other.tag + " hit OnTriggerEnter2D on " + this.tag);

                if (other.CompareTag("Player")) {
                    PreferencesManager.getPlayerController().gainScore(SCOREBONUS);
                    PreferencesManager.getPlayerController().gainHealth(HEALTHBONUS);
                    PreferencesManager.getPlayerController().gainCurrency(CURRENCYBONUS);

                    GetComponent<Animator>().SetTrigger("shouldDissappear");
                }
            }
            virtual public void OnTriggerStay2D(Collider2D other) {
                Logger.logPowerup(other.tag + " hit OnTriggerStay2D on " + this.tag);
            }
            virtual public void OnTriggerExit2D(Collider2D other) {
                Logger.logPowerup(other.tag + " hit OnTriggerExit2D on " + this.tag);
            }
            virtual public void DestroyMe() {
                Logger.logPowerup("Destoring char " + this.tag);

                if (this.gameObject != null) {
                    Destroy(this.gameObject);
                }
            }
		}
}

