//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
namespace TikiBeeGame
{
		public class SpeedBoostController :PowerupController
	{

		// Use this for initialization
		void Start () {
		}
		
		// Update is called once per frame
		void Update () {
		}
		
        override public void DestroyMe() {
            GameObject go = GameObject.Find("GameController");
            GameController gc = null;

            if (go != null) {
                gc = go.GetComponent<GameController>();
            }
            if (gc != null) {
                gc.numberOfSpeedBoostsSpawned--;
            }

            base.DestroyMe();
        }
	}
}

