//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
namespace TikiBeeGame
{
	public class StarController : PowerupController
	{
		// Use this for initialization
		void Start () {
            this.HEALTHBONUS = 0;
            this.SCOREBONUS = 5;

            if (Random.value <= 0.25) {
                this.CURRENCYBONUS = 1;
            } else if (Random.value <= .1) {
                this.CURRENCYBONUS = 2;
            }else{
                this.CURRENCYBONUS = 0;
            }
		}
		// Update is called once per frame
		void Update () {
		}
		
        override public void DestroyMe() {
            GameObject go = GameObject.FindGameObjectWithTag("GameController");
            GameController gc = null;
            if (go != null) {
                gc = go.GetComponent<GameController>();
            }
            if (gc != null) {
                gc.numberOfStarsSpawned--;
            }

            base.DestroyMe();
        }
	}
}

